keys:
  - &admin_pongo age1gvfnvnea09c8nqg7jf6m6e04e0kz0w4w4fvms00226cf7806sa2szcm46s

  - &host_zephyr age1fjuvtyar38325jh7cxg88tgylkpxamm47vk32m33h454n03zzezqgs84e3
  - &host_gopong age1qdvcmhrn9w6lw92ta2vmh55t077m38gs4ksez489ztvnfqe03gxqzy57rz
  - &host_jupiter age160pcykckysy5j9tksqpm3yr5l70xrj6c070ea3r39c6gza94hg7stnjkhq
  - &host_rpi3b age19th9vdcnftl5y2dwt8sl89xy7w5trvemxd7hm55glvqcmhh0348qef7pz3
  - &host_starfish age1j0e4y7cy9rutuvr6spkell45s79m0gwm27q93m6hymhmshkf65wsm4pfnm
  - &host_silverfish age1den7w9ceeyprqug0zmefjfmspaxjee6j0rmpg9r0e66d2rfu73uqk4p0nh
  - &host_wsl age1f2qg0qhff59k8pqzajx92fcxzrn2yqrfzq4gmjlrkjvrw97l7gcqmx9g4q

creation_rules:
  - path_regex: secrets/pongo/default.yaml
    key_groups:
      - age:
        - *admin_pongo
        - *host_zephyr
        - *host_gopong
        - *host_jupiter
        - *host_rpi3b
        - *host_starfish
        - *host_silverfish
        - *host_wsl

  - path_regex: secrets/pongo/gopong/
    key_groups:
      - age:
        - *admin_pongo
        - *host_gopong
