keys:
  - &admin_pongo age1gvfnvnea09c8nqg7jf6m6e04e0kz0w4w4fvms00226cf7806sa2szcm46s

  - &host_zephyr age1fjuvtyar38325jh7cxg88tgylkpxamm47vk32m33h454n03zzezqgs84e3
  - &host_gopong age14ruhfkzdehw0mmzdddgtsfr5zcs4xmmvqrt5u9563q7q9p94uprspds9k0
  - &host_jupiter age160pcykckysy5j9tksqpm3yr5l70xrj6c070ea3r39c6gza94hg7stnjkhq
  - &host_rpi3b age1tl35pllv9mu4nzk8hpa2uuul96njqrcttg4hw20902saf3uynueshux230
  - &host_starfish age1j0e4y7cy9rutuvr6spkell45s79m0gwm27q93m6hymhmshkf65wsm4pfnm
  - &host_silverfish age1f9y45fnympaytza0q59xzpqtqm6ac8uwxe55vc37xdllpwdacq6sy3wv3h
  - &host_wsl age1v5smpsnjafylktdmxga6kmjtwawcd8veeq7my88ltdfss9x2nfaqq70ske

creation_rules:
  - path_regex: secrets/pongo/default.yaml
    key_groups:
      - age:
        - *admin_pongo
        - *host_zephyr
        - *host_gopong
        - *host_jupiter
        - *host_rpi3b
        - *host_starfish
        - *host_silverfish
        - *host_wsl

  - path_regex: secrets/pongo/gopong/
    key_groups:
      - age:
        - *admin_pongo
        - *host_gopong
