keys:
  - &admin_pongo age1gvfnvnea09c8nqg7jf6m6e04e0kz0w4w4fvms00226cf7806sa2szcm46s

  - &host_victus age1gvfnvnea09c8nqg7jf6m6e04e0kz0w4w4fvms00226cf7806sa2szcm46s
  - &host_gopong age1l4sknz73q64rz2gy59d92twvs07p3tql4utx77fudxt0qsrl24nqqk4fqf
  - &host_jupiter age1ma0e5ap4pdqmz4qj7rttlrk56mcvka0tuvltgp7dcv73fu6q3q5qj99gun
  - &host_rpi3b age1tl35pllv9mu4nzk8hpa2uuul96njqrcttg4hw20902saf3uynueshux230
  - &host_starfish age1525qyyhynpsqq9uee9yqhkt02kqnmpm8w4nyaw5wraewwrlycdjqg800wp

creation_rules:
  - path_regex: secrets/pongo/default.yaml
    key_groups:
      - age:
        - *admin_pongo
        - *host_victus
        - *host_gopong
        - *host_jupiter
        - *host_rpi3b
        - *host_starfish

  - path_regex: secrets/pongo/gopong/
    key_groups:
      - age:
        - *admin_pongo
        - *host_gopong
