# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = ["xhci_pci" "ahci" "nvme" "usb_storage" "usbhid" "sd_mod"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-intel"];
  boot.extraModulePackages = [];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/6b5fbcaf-dd85-42e1-80aa-d4dd304c1c66";
    fsType = "btrfs";
    options = ["subvol=root" "noatime" "compress-force=zstd"];
  };

  boot.initrd.luks.devices = {
    root = {
      device = "/dev/disk/by-uuid/5ce689b9-15a6-488b-a3dd-465c877e65f9";
      allowDiscards = true;
    };
  };

  environment.etc."crypttab".text = ''
    ssd     UUID=0b226cbc-287c-41cd-8377-a92a2de416ba       /persist/keyfile    discard
    hdd     UUID=065c2b5a-3b56-478f-b5e0-b3b5c6a78ff1       /persist/keyfile
  '';

  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/6b5fbcaf-dd85-42e1-80aa-d4dd304c1c66";
    fsType = "btrfs";
    options = ["subvol=home" "noatime"];
  };

  fileSystems."/nix" = {
    device = "/dev/disk/by-uuid/6b5fbcaf-dd85-42e1-80aa-d4dd304c1c66";
    fsType = "btrfs";
    options = ["subvol=nix" "noatime"];
  };

  fileSystems."/persist" = {
    device = "/dev/disk/by-uuid/6b5fbcaf-dd85-42e1-80aa-d4dd304c1c66";
    fsType = "btrfs";
    options = ["subvol=persist" "noatime"];
  };

  fileSystems."/var/log" = {
    device = "/dev/disk/by-uuid/6b5fbcaf-dd85-42e1-80aa-d4dd304c1c66";
    fsType = "btrfs";
    options = ["subvol=log" "noatime"];
    neededForBoot = true;
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/9575-D217";
    fsType = "vfat";
  };

  fileSystems."/media/ssd" = {
    device = "/dev/disk/by-uuid/31b51531-24cb-4532-aef8-8c866f08e178";
    fsType = "btrfs";
    options = ["noatime" "compress-force=zstd"];
  };

  fileSystems."/media/hdd" = {
    device = "/dev/disk/by-uuid/c3a302d7-34c8-42c3-98c9-f8e38f0ba245";
    fsType = "btrfs";
    options = ["noatime" "compress-force=zstd:6" "autodefrag"];
  };

  swapDevices = [];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp8s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp9s0.useDHCP = lib.mkDefault true;

  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
