emails:
    pongo: ENC[AES256_GCM,data:QDTnUDTeXCBApwW5wOd9ruN66Qv/OgOh9oUiLP6X4pBUNSpzIMpREaEDhYVovGY0ieXeaSkOyayoTdVaWg4I7JVKAS3EP9VjJg==,iv:903io8Edv5UDF/Fu9oeoAEEVAQ4A+JM0pYpcwlJz5Nk=,tag:B8r0gVwVZ9eaSxjrx6X5fg==,type:str]
    ec: ENC[AES256_GCM,data:Wd8qhyt2T+BvvuTxT2qokw7mMO5NUQASVpv8yq/jLP1RKljSwC0bx11j4Z76TTCi2zsFPZIHufkaIOvXEewRfG+/CiQ+65grvQ==,iv:TLm4QEZtlBpzAzL2CbKd1kl8wO0IwCgI36Wot+Q9YtU=,tag:RZbqvmAFN9MQf3uDqBhShw==,type:str]
    no-reply: ENC[AES256_GCM,data:YNEXrgEuWgOUi+e0Eh+OrTp2V3JmY76Uk8BUYSpwjyOblKc0r2/tNhrDfuhTfkl0+b8hBWeQkD/eRTAawHN4PwWy0gejcPrsWA==,iv:Za1HttZWwRaX0euIh7SQr0fwl47keuRGAPSnKXUQpVg=,tag:7fPYY9XWD6D2Xr9neIcBNQ==,type:str]
    chaos: ENC[AES256_GCM,data:HJUbmfKwI2UOVE3PnIhblpU7R3GLyYgzak5AIRxDJawiTiYgRbq4xvRVSlFdsmkAXEEkSHVrAalBhenD7vqviBvI3SU7gMXNuw==,iv:UuFwJLIH0GlyQJC3bwWhucKg9d7LgxS+wVGtQPG2zIU=,tag:uid1onR0T+knvUFKJwAFjA==,type:str]
nextcloud:
    adminPassword: ENC[AES256_GCM,data:L1DQNFp+DjyCJyYgLS+n,iv:eTt5otuTGL3YqZNBqHnc8SftOWeX5OZqKEb4KfNsQUc=,tag:vCqWX94/YNWvPp13ONTaVg==,type:str]
discourse:
    adminPassword: ENC[AES256_GCM,data:ph6OBCHYxhdcEDa65u/K,iv:RbShQifERzJ5nZWSEMWbrTGFID6URW9kEDGKIc0eT/Q=,tag:dxrxmmzIg/MnadSZ0ZRO4Q==,type:str]
    emailPassword: ENC[AES256_GCM,data:SSVkJQv4Pnnv21FUfZs=,iv:+tUKta1BS49MzKm0QjELp3k18cGOjR3G9Amx8vX5Nt0=,tag:g/AGu43/gFYtrYPwM0DrjQ==,type:str]
    secretKeyBase: ENC[AES256_GCM,data:kKzTePV6JVkdMfeVYWjI96BC0eO3cq3sU4SEp0BYll9+WNuiRPEQPoV/QJ8GPkP/aPoiKLBG+nxqIGsN0RoC7jFSJGvwEWkCm5RT6P3IIhlXv+eUIlcJM+XxoD68cYDMi8VVOkgAIB696WCqij+d6wYY9N14SErRI0XBCWT1uro=,iv:auKXHfgM26DOtks0CihhzuTqoUfNFvzA6adRNMGvxRQ=,tag:BFLTmlpjPo5Tgf2RDAmtyQ==,type:str]
gitlab:
    rootPassword: ENC[AES256_GCM,data:FgJr8+jL1nFQIK/k6nVylnIpAQc=,iv:E02/LoDh+JS7r5awGfVRK5EHs6/ysTlinCZOjfSkPFM=,tag:rsFhJCPawG76AJZcBnf/bg==,type:str]
    emailPassword: ENC[AES256_GCM,data:KwxJvjKcXR3O0YN5NPg=,iv:Aqsxf+nmixcd0yHnQYB7LLonT3LYRNbfCCGmRc7BRNo=,tag:KPhpAiZkWG/o7na+x1AZhg==,type:str]
    dbPassword: ENC[AES256_GCM,data:unDQifDeteSuZ4Gb+KT4hGveA84=,iv:E8lcvruvTRnJlsRp5ws8oNCzB2AdqG1lpiy060+mBXM=,tag:n+v7RBxS2AoBp9ftDnpXFQ==,type:str]
    secret: ENC[AES256_GCM,data:1N7dLeQM8O/7c5cmP61VxtzhOyg=,iv:l2Mct9firBeBSW5fWWe8OmBOXE+z2sUx9W5SLeIe9DI=,tag:lMmN3C298kf5HWIec1WxuQ==,type:str]
    otpSecret: ENC[AES256_GCM,data:EsKa1UM/csg0+UQKFOC9ckL9EmQ=,iv:026RhScM87L11fQuMj4KIKm2DH22sTNAPsTJyTIxl0Q=,tag:2jG058K3DEMX8uT6vv+a0g==,type:str]
    dbSecret: ENC[AES256_GCM,data:cPECN5m2amuUgYzxHO28Do8YpSQ=,iv:/2FNdsUgJDcuKIuC8QpzFihhsJ1Mlopl1VQPzCDkJfs=,tag:yksBuA7OiYm+7J5x3wXKYw==,type:str]
    activeRecordSalt: ENC[AES256_GCM,data:jJ6Tgxa/eWBQ/HhP5vNVtFKe3eU=,iv:VJzRsLzgK35+4ylqP5AdVfjeScICDcKwX8nYaIYgaCE=,tag:gHRQC1ZNkE7t5nZcAAUTjw==,type:str]
    activeRecordPrimaryKey: ENC[AES256_GCM,data:M3X0mQktTYPelMyiZigptRY4Axs=,iv:EEo4uW27EJwvSYM7KJJ6JMzf4ffnVFQ60WvT5Ixuwl4=,tag:GpAsmOEbbElvTvx/DGY8/g==,type:str]
    activeRecordDeterministicKey: ENC[AES256_GCM,data:eTBRpTr6rFBhtfvttc5MuusUnns=,iv:fno3kRDNhyc/Jm9H6aryOBUDuQ9/tVAb6/P7rvxDy2Y=,tag:NHTuvG8ZXNyCtwkLAlRnUw==,type:str]
sops:
    age:
        - recipient: age1gvfnvnea09c8nqg7jf6m6e04e0kz0w4w4fvms00226cf7806sa2szcm46s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4RWFmYTRuaUhFRlh1a0hx
            QWhQbU1pQ2s4SHVtTTVVb3B5TEJtbHdDeVN3CnRuV25zeHRzRDNNcDVEQmhpUlVF
            Nmg5MGFBdG5hMk1PYUtkaStVZUVKQkUKLS0tIEFiODhoV1NoOHl6ZjdmVVhSbmNS
            TVM3bm9tMklPVUhKUUhlcWlqbGFyaHMKQZzRL9vcolcvlw8o+CWMvGVRXe/OvQvj
            2P06CWkaZd1B2XcHgfee/5mrKt2/Eekr0W3/BR/93oEjHlO5Ggmmtg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age14ruhfkzdehw0mmzdddgtsfr5zcs4xmmvqrt5u9563q7q9p94uprspds9k0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1ZXYzQWtrZ1Nib1M4REJL
            RkpSYTBLOWt3dTJ1aXRXVmVsaDAzM3Q4cTFrCjBUWXcvVW1meWpreUpPc2wzRThu
            Q0hkV1E3dHU3NlNtUnNoS2pXY3pGNlEKLS0tIGoxdHNBTTVYc1JtQWJNb0hvOUx1
            MVdMclBUK0hjbVNENGsxcVlsdzY5Qm8Kk5IWuJTCig4KOo8Un/wPH77x0O7PbqlC
            xNyPw8msEHuwUDYsf787WTjUyCk/pr0uIL+dRpOsZvutjro/sAFD0A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-22T19:51:24Z"
    mac: ENC[AES256_GCM,data:CPYdpozld1fITVIA4q9R0chaaSmnK5UyfArgMXYAyHSK8D4GgLVPJHmMrG/IkhFOAITI3Wz7yjD1UZIuj84NqzvboJc4ge7o3mv5R5uD7VhefVQa1ONsjOyrN6N1WNGfIU8L7fpiJDcFgV1IGqSlLqZ+GIsxCkNp/nnbc1Jd0z8=,iv:cB3kYvT4tSad9x//QGSdYZQek6Wgz8Pl59LTVzqvwZE=,tag:jEdMFml6oPn2JsFYT4ZGRA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
