emails:
    pongo: ENC[AES256_GCM,data:QDTnUDTeXCBApwW5wOd9ruN66Qv/OgOh9oUiLP6X4pBUNSpzIMpREaEDhYVovGY0ieXeaSkOyayoTdVaWg4I7JVKAS3EP9VjJg==,iv:903io8Edv5UDF/Fu9oeoAEEVAQ4A+JM0pYpcwlJz5Nk=,tag:B8r0gVwVZ9eaSxjrx6X5fg==,type:str]
    chaos: ENC[AES256_GCM,data:HJUbmfKwI2UOVE3PnIhblpU7R3GLyYgzak5AIRxDJawiTiYgRbq4xvRVSlFdsmkAXEEkSHVrAalBhenD7vqviBvI3SU7gMXNuw==,iv:UuFwJLIH0GlyQJC3bwWhucKg9d7LgxS+wVGtQPG2zIU=,tag:uid1onR0T+knvUFKJwAFjA==,type:str]
nextcloud:
    adminPassword: ENC[AES256_GCM,data:L1DQNFp+DjyCJyYgLS+n,iv:eTt5otuTGL3YqZNBqHnc8SftOWeX5OZqKEb4KfNsQUc=,tag:vCqWX94/YNWvPp13ONTaVg==,type:str]
discourse:
    adminPassword: ENC[AES256_GCM,data:ph6OBCHYxhdcEDa65u/K,iv:RbShQifERzJ5nZWSEMWbrTGFID6URW9kEDGKIc0eT/Q=,tag:dxrxmmzIg/MnadSZ0ZRO4Q==,type:str]
    emailPassword: ENC[AES256_GCM,data:/1KovVUSuEkU9cXe3sg=,iv:Y7hMinIazJecZL7T4LoCcSSqWEmDjKSFHzWC89m3WgI=,tag:8TQK0JOsKnzn4a8Um/VJmA==,type:str]
    secretKeyBase: ENC[AES256_GCM,data:kKzTePV6JVkdMfeVYWjI96BC0eO3cq3sU4SEp0BYll9+WNuiRPEQPoV/QJ8GPkP/aPoiKLBG+nxqIGsN0RoC7jFSJGvwEWkCm5RT6P3IIhlXv+eUIlcJM+XxoD68cYDMi8VVOkgAIB696WCqij+d6wYY9N14SErRI0XBCWT1uro=,iv:auKXHfgM26DOtks0CihhzuTqoUfNFvzA6adRNMGvxRQ=,tag:BFLTmlpjPo5Tgf2RDAmtyQ==,type:str]
gitlab:
    rootPassword: ENC[AES256_GCM,data:FgJr8+jL1nFQIK/k6nVylnIpAQc=,iv:E02/LoDh+JS7r5awGfVRK5EHs6/ysTlinCZOjfSkPFM=,tag:rsFhJCPawG76AJZcBnf/bg==,type:str]
    emailPassword: ENC[AES256_GCM,data:AtHhdsi+3tdD6IE6eqY=,iv:5aqJLeFqKKVXhhPNeQLS3uhPJnBnAmi7E0aY0d2qF1M=,tag:UpBOP7n/A9aNWRDefcUeIQ==,type:str]
    dbPassword: ENC[AES256_GCM,data:unDQifDeteSuZ4Gb+KT4hGveA84=,iv:E8lcvruvTRnJlsRp5ws8oNCzB2AdqG1lpiy060+mBXM=,tag:n+v7RBxS2AoBp9ftDnpXFQ==,type:str]
    secret: ENC[AES256_GCM,data:1N7dLeQM8O/7c5cmP61VxtzhOyg=,iv:l2Mct9firBeBSW5fWWe8OmBOXE+z2sUx9W5SLeIe9DI=,tag:lMmN3C298kf5HWIec1WxuQ==,type:str]
    otpSecret: ENC[AES256_GCM,data:EsKa1UM/csg0+UQKFOC9ckL9EmQ=,iv:026RhScM87L11fQuMj4KIKm2DH22sTNAPsTJyTIxl0Q=,tag:2jG058K3DEMX8uT6vv+a0g==,type:str]
    dbSecret: ENC[AES256_GCM,data:cPECN5m2amuUgYzxHO28Do8YpSQ=,iv:/2FNdsUgJDcuKIuC8QpzFihhsJ1Mlopl1VQPzCDkJfs=,tag:yksBuA7OiYm+7J5x3wXKYw==,type:str]
    activeRecordSalt: ENC[AES256_GCM,data:jJ6Tgxa/eWBQ/HhP5vNVtFKe3eU=,iv:VJzRsLzgK35+4ylqP5AdVfjeScICDcKwX8nYaIYgaCE=,tag:gHRQC1ZNkE7t5nZcAAUTjw==,type:str]
    activeRecordPrimaryKey: ENC[AES256_GCM,data:M3X0mQktTYPelMyiZigptRY4Axs=,iv:EEo4uW27EJwvSYM7KJJ6JMzf4ffnVFQ60WvT5Ixuwl4=,tag:GpAsmOEbbElvTvx/DGY8/g==,type:str]
    activeRecordDeterministicKey: ENC[AES256_GCM,data:eTBRpTr6rFBhtfvttc5MuusUnns=,iv:fno3kRDNhyc/Jm9H6aryOBUDuQ9/tVAb6/P7rvxDy2Y=,tag:NHTuvG8ZXNyCtwkLAlRnUw==,type:str]
sops:
    age:
        - recipient: age1gvfnvnea09c8nqg7jf6m6e04e0kz0w4w4fvms00226cf7806sa2szcm46s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoTlRTenU5b1FHbTdVN2xJ
            SEZ0OXpPWk5BblMyQ200ZHVLM2xxQlJRVDJVClNFMDBJTlh2cldOMzlCZjlNNVMv
            dVhVeWlMbmNJWHdXR21abTd0WlZicEEKLS0tIGM5L2k5OWZpVGhSV0Z2MExlR2JW
            YjRwb2tZUnlVa0ltOEt0VGFUQlMwVzgKoNKxqWVAhw3PSbK5hj61SY1eY5dUi7Gy
            LgUsj1hGKSuunKNeXGizKRRkRqba3lUZKVhOc4e0GUHH1Q23GyHsNw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1l4sknz73q64rz2gy59d92twvs07p3tql4utx77fudxt0qsrl24nqqk4fqf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOTmRWUVp0b2ZUZ3pULzRx
            akFTUC94cVNwZXFCTndiaUpCVnNvaitCWFM0CjFaOTkxYmp5aUV2ZVkrR25CNXZ2
            dThaRHUydVBnQ3ZCM0h2NmFXK0RhenMKLS0tIDBLdzQ5RmFKVHZwZ1lkNmFVakdp
            N2s1UmFVNnlCTDd1WklHcUlTWUJHRnMKcI+7VN01jntrMzQ6IUwm121pKCr8w2XD
            h4h0o8j3QfYvS+WwgW8DwwLjjtUuSJA6oHYXeO4/Hqb3XuS5KJl2zA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-09T12:24:53Z"
    mac: ENC[AES256_GCM,data:7B7txIeXjY0DJvMKTsF88UfzKsCs+iROWwO724IHEysSpA+9fEyD2QczBfC2fHBX7R53/isIKJAJGmbgGjLGk6hbAYEFWs/FRzOuaFVmHMg25LNjVDqvrA8hTLlTHO2c8z08zJivHxy9xek9iVbEEQYQawmjrub3CnuBR4yRDag=,iv:cGvG+is4xPTnqyCoJ83e0wuF+7g5YIQkYrI14bFLXRA=,tag:RONzi/aVApZ8hZmDGFEUtw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
