base:
    userPassword: ENC[AES256_GCM,data:uzbuf4cWuYl3HLCRRqvlzButLtDEavlbfM9F899A3KaddV4a+JxoKKIt0D1DB5FKEDvRab5NwBsNC8ttopBDauMEK6cojHw6yQ==,iv:D8i66+rvjpULAEOQ93jtdHXP0xISyvGFKbkBCiLb9v8=,tag:qM/+0g+SvU+a3FB6yX9fJA==,type:str]
sops:
    age:
        - recipient: age1gvfnvnea09c8nqg7jf6m6e04e0kz0w4w4fvms00226cf7806sa2szcm46s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBualE2VWU1VGk0VGh4RDQ2
            S0duU051eEw5RTN1ektxUWlJcWJ4eHhpM25FCmgyQ1ViZnhIT1U5MUg1MGtuRFhI
            WWtWaFdJTHJjZnU4QnFCakRmaEh0KzgKLS0tIDNYZy9Ka0V4RnNRdUJvUis2UGZZ
            T1JHaDZGMlRyUW5SbVRYUkZIQ1FsMmcKWkmGwas4u0srAaHvkC1vO3+jmqneAkxg
            5axicby+gCFQT/uS/tnJ+Az0Lvgpet5QCdOzwonMhGQX97o7nFaX1Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1fjuvtyar38325jh7cxg88tgylkpxamm47vk32m33h454n03zzezqgs84e3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzek9iTTQxOU5pSmFxc3N5
            eGx4RWIvZG1ON1p1aWowVVBoN05iTjJ4U0RzCjVxOEFwR3BzN1pVTFJKOCs1Q0Iy
            cDc0OVRlenUrZ0VWd3RFNjA4K1dPeDAKLS0tIFZ2ekQzSkZ0UnBsTWtGQi9lcTBh
            STd0Rlo1QUV0ZWFIUnh0ODBrWEdpb1kKRA828DwHVOUnu1mEAPm5sOC8+OPbJ63A
            ksoQTj8u0MP53w36c2kJymTs2Y3cWPh+0Ms7E9FyLrI2FRITp1GiXA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1qdvcmhrn9w6lw92ta2vmh55t077m38gs4ksez489ztvnfqe03gxqzy57rz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJUFU1aFo2NzdpZzQ3OEts
            VVZ4WmVBK2hyMGE3Nm9QNFV4dEVQb0thOGpjCit4bk4xMFZFblpsd2RSeGNhQ2Y4
            ZHZmMmRzWGVJWFQvZ1NVOXZUcC9xV1UKLS0tIHMxazVnTkQ2aExtaEFSeHI3VWJL
            dmFYdGora0hiclprZHUyTml3OHhhTEEK+aDQ7bhnvr8EDJ+8RmBOzgA78JTTaKqe
            k6l3XFgSixxuvqCrWO5i7YRHWF79p88LCWX2p1b9QZfHfLLUBaF54g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age160pcykckysy5j9tksqpm3yr5l70xrj6c070ea3r39c6gza94hg7stnjkhq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlK0pDSzZ4OGt2QzliUXBQ
            YVJtaDNjaEFPVk5md1IrNnpyRGdBNHVKT0N3Ck82bVNNbXp0Z0MrUTlyb2hZYWdT
            bzdsemhxYVJnSVIyUklZeW5ueWRpMlkKLS0tIEY4RVdQTVkyeGQ1SkFJM0JxOEFQ
            WDJWSlJiNnFVbkNZRXVKdWdsWDN0c2cK168Y1MoDJ95PDWpk4NxOTV7zrl9yqJO+
            0mH4ca4h1MLfZI5xBlaOzSgdYmmUg/G7vgwCyCpeLJDLk80CTgeLyA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age19th9vdcnftl5y2dwt8sl89xy7w5trvemxd7hm55glvqcmhh0348qef7pz3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAydVFXRW1FRmZwdWdGeWx1
            MG1VYXNYQ01zcVkrQ2dnQ2RaVHF0dnYzNURzCnRWRVgrc3lnVmJhbXNGVkE4UVla
            ekNvUVY4VjJZMkI2RWZtZFlMQW03NkkKLS0tIFpSWjQzc2FXbXJacFNML3hIaWVP
            T0g2UW5MV0FlWXgxbStYVE5JNmhJOTAKDl82kXYK9v7ftC5NjacrtGRudhbRB4hH
            wNHm+OI1N1HABCKGIHfXlUqTMz9zZw0nLv9GVFFEZqet3xU+FXvsVA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1j0e4y7cy9rutuvr6spkell45s79m0gwm27q93m6hymhmshkf65wsm4pfnm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCZTNpRG14V2lycXNLdi9t
            aHhoNWY3TkJVNnJvOXZLL3RqR0s4VFkzbVdjClBvS3lnZUd6WkRCdzJ0S2d1Qyt4
            L0VkQkhVN3AyWTZWUld4b2I3Y2JoYmMKLS0tIHVkQ3d5TXF4SjVqR29YUU1vbldU
            WFdwSy92L2FDMGtMckExZUh4T3JOdGMKuEE5zJ8NIJqOSAeyVe3fbBZFIljIavrf
            wjIsh2PyxbO56RTA905e9DkkDZvfIQ1b6QbYVEnX4oxc65RYLw78JQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1den7w9ceeyprqug0zmefjfmspaxjee6j0rmpg9r0e66d2rfu73uqk4p0nh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4R1NhblhXR1I3YkxVNi9v
            aVp1TmxYNml2YXNiellpL0ZPWXA1ZEFCZnh3Cm5tZHh4dlNyVWpTR2IzcHZMQlRj
            aTdHNi93TVhVdEFUbDdJT21BU0ZEOFEKLS0tIG1TMTMzc0o4d2RGa21BYldBblBt
            d01zcGk5ay9LWXNjbTdsWkNNdzg4TncKJWrqpiROzld2f8/5KFJbMVxXpPcVctsp
            r505JTtk4D7Un7wYqOpn6mX7JmJDDRUBcOMSLdeCYOGJWQTabfHQNg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1f2qg0qhff59k8pqzajx92fcxzrn2yqrfzq4gmjlrkjvrw97l7gcqmx9g4q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2NzkrUEhPY2ZCSXRHOUt1
            SEIvbnhVSnQvdzRpeHFzRGxCWFd5aUNLTlFJCkVXQzdaRmJnYWJEZ1QvK203RmlT
            aHVhV2ZQdm9PZ2VGUms1S3FqeWlLSGcKLS0tIGp3dkgzdUhvaW5nVHhDczVXZDk2
            d0dQTW5BWmdpMEZPcllYSHpkWXdXL2sKtXSuOC2v32b08K+HxzDFKf+XvoaVMKcV
            kWIXbcR5mQJlgL0Z6A+NP5b3JpkkWtpnqW/0K2WCk+BfphLDk24uFQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-27T09:52:07Z"
    mac: ENC[AES256_GCM,data:eDniaSkuBMuU1Te39/guKH1anN6N7mmqIMwj7LckJkPvTaBASstaRuJzrQpHjWQv85pLbPLPkaSzebKpq3HRebCYe4akkMY6gi5KrNa6uyV4dXZNZkxYvGtT+RBo61lwoadZlug9pVu3UYVQDsLlszlLruyKLqtQ6rbhDrXF84w=,iv:TRxpwCHXeadlcmcQRCPRO9xPcq+Uw3PxSfOuSmyidyE=,tag:e3R1BN1/C+0grO3vYXCctQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
