base:
    userPassword: ENC[AES256_GCM,data:uzbuf4cWuYl3HLCRRqvlzButLtDEavlbfM9F899A3KaddV4a+JxoKKIt0D1DB5FKEDvRab5NwBsNC8ttopBDauMEK6cojHw6yQ==,iv:D8i66+rvjpULAEOQ93jtdHXP0xISyvGFKbkBCiLb9v8=,tag:qM/+0g+SvU+a3FB6yX9fJA==,type:str]
sops:
    age:
        - recipient: age1gvfnvnea09c8nqg7jf6m6e04e0kz0w4w4fvms00226cf7806sa2szcm46s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxSEgwcVlKY2hJZjJ0eWFM
            TzNiZ3BpU2RVWmVvK1FWczNpeXNPODNyMmtjCkFwa3BveklBUm80eGtDRTVYOGta
            NUNSQlUxQXREbXdjTklrVzVqa3JaWEkKLS0tIFVEZ2RsYjBZWmo1UVJENHVUK2pP
            dktpMjNIcUY0cXZ1MXRvZVdJdXpNbE0K3uKiWBuXEP9RVPC2FG9Yc4dxwNEa+FiT
            Lrk+laW91Pyj3d6lWXdSa1o3WWjDbpyLx+rUtkI+Alupy+8tzx2h6A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1fjuvtyar38325jh7cxg88tgylkpxamm47vk32m33h454n03zzezqgs84e3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3MURtcHdGUFhoamUzVzFz
            SzRhWDV5SjVuaTdmSHM5RS9mQm1GWEFId1RNCkphUGRmK2Q5ZUZ4VWJNVzdwMVNM
            bEZXL1A3VWIxYU5OSDZSa3A2Mk40TjQKLS0tIG9vak9EbEJTc1hiL3BFTEdRQ1Vu
            Ujd4SHJRWENCRHBXdHdGeWVjRFYyRk0K6rhjoJeef/dRh9QU2F00ajJHfSG+nX7K
            2x8g5M0giboD7xxxz+4tNixCh/IpAwIkdt86RiZVsAAJT8nlcIeRWQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age14ruhfkzdehw0mmzdddgtsfr5zcs4xmmvqrt5u9563q7q9p94uprspds9k0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFQmtDT0lWV3FwMGx0NTUx
            eHFCYldpbTRKYVJhUHEzTkd6MFRSaUVQdTNZCmdNbHcvOHFvbXpJTzB2blkxT29H
            M0FrVlNiY1FMTWN5djB4aVJTSnlWZU0KLS0tIFQ1U3RiVDJQNXZEK1VsY0dzTVZN
            VUlqdVFnNHBtYlRqdHUxS2lZejhZaWsKSxqHo3/DDcPzF6TOiGxDI9J/og0YIfGW
            Riq/byUcq9Be2rHNjw5uIc1Ko/otHajHmTEk+gQrWi91nTbK1bcY1Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age160pcykckysy5j9tksqpm3yr5l70xrj6c070ea3r39c6gza94hg7stnjkhq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZS08zeGM4VjhTdms0cFU2
            Mit6a1lDSWJIUkF3UGFQRFBkb3RQb3ZSeVdRCjRNaXFUZUF0b1RGckFqalhwSjZF
            SCsyd1RoZzYzdkR4aVhCNm4yNlhpM2sKLS0tIHJCRU9aakRBUHc5amVKVCtCUFVr
            Zmo1NlQ3bGdZWHl0YVdOUUJyN0cvOU0KXu/nNhJg34tOMske13mINuKlhQ11k31y
            MsEgE0A8J/9KL1UJOJeluRvJv1ZVxbIuX8H2Zz9fG0KglSfFwi+caw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1tl35pllv9mu4nzk8hpa2uuul96njqrcttg4hw20902saf3uynueshux230
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWMWY0WWVxV2QrN3VsRzEv
            WERFRG93azNVSDZnd0puZnVGamFOUDlkaVRNCjREMTYxeUtjSmlYR2VpMjFWT0JL
            d0ZHUnlUNHAvckpOTnRqR1FrM0gzZncKLS0tIC9ud0VwbGlGc3BQRmdmRGhvV3ZM
            RksrZVY3SnZGL3lEbmVDNWswWFlxT0UKjhqQK6U6oYUlLCH4EmTXk0TfaPRfM+xa
            gQ648rXEeW6Sy3IyrtXkq5T56IkSxSPOKHaHaxnPfbMYs6H+J5mgzg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1j0e4y7cy9rutuvr6spkell45s79m0gwm27q93m6hymhmshkf65wsm4pfnm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLamxLOGsxY01tMlZHbzVp
            TC9ER283cFpnYkhVZW5EUURSNW4rUlFkaUg0CmNUL0pVUGIydGRGVHphNW1LWFA0
            bkliUnc5aFgrUEpCR2ljaEcybmM1ZU0KLS0tIGp1WjBtTTh1elRuYlRFWDRsOWQz
            SDhPUG9iK3E1ZklRdks3UVpSZ1RYK1UKjut5lSdAg3lV6pquuOAEz/SntptLOBIQ
            NU8x59muOoWj1TRFPLHLkWtuOjsMMW1LoRx/q68e0v3dsDAC5B9wqA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1f9y45fnympaytza0q59xzpqtqm6ac8uwxe55vc37xdllpwdacq6sy3wv3h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLRFVnZ015K3Fxa04zbDNw
            R3FzakNPWW51T2VRSDVvVWNDR251anhoaURjCm81dXZtU0J6UUJiMWhWRTBXSmlh
            TG5ocjRLUi9RV2FmRzBsNEdVUXJHTE0KLS0tIHZueVE2bVhsZkIxY0xTNlg2SnB3
            M0RWVHZlSGZKSE5oenZXVzRRYk94aDgKTE3UjtBwbKiiYbKrHMxIDgrwxl3v7jxA
            gOkVnwsogh/Hw0ap1DbeL2nBX/NVvJYiUYjRu+FF1Q3yjT0GvnotsA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1v5smpsnjafylktdmxga6kmjtwawcd8veeq7my88ltdfss9x2nfaqq70ske
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBZFJHNG5BQUROZXpJT3Jw
            aEdyWEs0OVlNRjFUckdMYzNPaVVGSlJobzBzCmw0aU5aSGR2VkJSc0wvYy9hdFl0
            OGZrSGlCZkZZcnlWb1B6dGJVWUpJT1kKLS0tIEkxOHFqeXY2WE1seWp3MjBJazlZ
            UXZDMEFvS0RGcFRSUkpWcUhrcHpCMkEKsH3Ze1p8TRjk4PGxhxseE+afGDFVGJq9
            MfGG6TYLN+CpgWdxVhUBCzRvDRf3RWT5S1iurstinCVHq06sKLux2g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-27T09:52:07Z"
    mac: ENC[AES256_GCM,data:eDniaSkuBMuU1Te39/guKH1anN6N7mmqIMwj7LckJkPvTaBASstaRuJzrQpHjWQv85pLbPLPkaSzebKpq3HRebCYe4akkMY6gi5KrNa6uyV4dXZNZkxYvGtT+RBo61lwoadZlug9pVu3UYVQDsLlszlLruyKLqtQ6rbhDrXF84w=,iv:TRxpwCHXeadlcmcQRCPRO9xPcq+Uw3PxSfOuSmyidyE=,tag:e3R1BN1/C+0grO3vYXCctQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
