base:
    userPassword: ENC[AES256_GCM,data:uzbuf4cWuYl3HLCRRqvlzButLtDEavlbfM9F899A3KaddV4a+JxoKKIt0D1DB5FKEDvRab5NwBsNC8ttopBDauMEK6cojHw6yQ==,iv:D8i66+rvjpULAEOQ93jtdHXP0xISyvGFKbkBCiLb9v8=,tag:qM/+0g+SvU+a3FB6yX9fJA==,type:str]
sops:
    age:
        - recipient: age1gvfnvnea09c8nqg7jf6m6e04e0kz0w4w4fvms00226cf7806sa2szcm46s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrWnlFQ3VaRnZOQlY3RHRy
            bllLOEdZVnhjM2phZGc5SWVGWXdOZjRaU1YwCmlHRlNLdkVnTFdJMGpTZWgrUVpx
            aGg4VWZPZmNBQ3BPckxEZ0dtRXRRSnMKLS0tICt6ZGZYQzRjNlB1aUQ4a0JoakE2
            REJVbUdxMm85VXY3NDFEMDBnalg3YlUK8VbiXu+GKocRy+6BzS/Ic5DPGKlY5vxa
            bzrXwTSdkjyPmZPxbnXSL+zrGw3JImdoOKGZg/FWEYuR8PZ3EoCPRg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1l4sknz73q64rz2gy59d92twvs07p3tql4utx77fudxt0qsrl24nqqk4fqf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvcXdFUER1VUdIL2Z0MHBF
            cjZHTkF0UFZNZktVS0Q1VFF5Si9ZVFRQckg0CmlUL0FlMGIxaSthVzBPRlJrNTZz
            NHA5bXpvMjhNK3NoTGw4ZFV1ajZDZlUKLS0tIHBKa0xTeWREM3l5Vks2dGJSenVz
            ci82UUJTTTIxalhUSkZha0ZSMUdiOFkKm7CvLPIfGbviF6+CPwP/yK3CSx2so6Dr
            0x0PwdKy5kwZ/HzOiDBEoSLMHRQICNC1Xuz51Lm5Td8QM6Kd+4/pIA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ma0e5ap4pdqmz4qj7rttlrk56mcvka0tuvltgp7dcv73fu6q3q5qj99gun
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzWnFvV095cjl6WXk4K0dr
            YVlkNGZHQ2ZxVW5CbWVPR1JkVzNKTm1wSUdNCnh4Q255UFNKN09FSGZ2Q2dBU0ND
            UERwbm1saHpsdTQ3ZFNqalJYSUlSRTQKLS0tIDJvQWV3TlZTSmxMR2J4RTE2dDh1
            ZGw3TjVHTVBkeXlab0M2bStoS2FIODgKzvS0G4YGUSGd/9kHeoYalHogPt3uLTlB
            IFjheCYyDu0GTOuZICc1tTcjJqVF5zlf9ORKblQ0iqiljS7OSIUrXA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1tl35pllv9mu4nzk8hpa2uuul96njqrcttg4hw20902saf3uynueshux230
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsYWJScVdyZElFbGk0cXBU
            VGw3THR3NTd5ZHR6M2NuVHozNmpWaGNQT3lRClQ2Q1FXSGMwajlTbzVxZTRIR1Nk
            Z0NSbkJLbU9LTjIvbTIwZGhKSlJUSFUKLS0tIGdTMnZBQ3hqelZjbkh5Tzl6Qk5J
            RDNqMmtmVTExY2dHSUZIRlEwcHBUbVkK6tdGxldlU45VZOcsVW2EYq0rdL8rQtzI
            gIEgXkrkz0O/VjCB4ziLaqFfe/Nj+hqfRhgolYwyx4Fd4OAQNUFQ1Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age17rwt27929gj3htrx3lta7xgpxr742mdalqk7n57xprqeszawppaqa3u2rp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2bUZrR3lPd0U3aTk1SWlk
            aEFYdEcydDEvd1hNZTBVb05CRXI4aFpCU2hrCjZPcVpzTjdnazBiT3VoNW1pcUFl
            WHhxNUtaSDFTWDFVSWFaWGt4SzNtd3MKLS0tIDdJL0g5SWhjQ0NTb3A4cmZpajdI
            YlVKZU12cFgzNnk2ZnNmY1RWQ1hPaGsKrze+9VqonvJD8MHk+d67Cyvg7qSx5gKW
            Vf24oKsb7rTedwiyjp/KVZaK+iZ3T4hSREDJu1YJhqV3TDIiGcErkA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-27T09:52:07Z"
    mac: ENC[AES256_GCM,data:eDniaSkuBMuU1Te39/guKH1anN6N7mmqIMwj7LckJkPvTaBASstaRuJzrQpHjWQv85pLbPLPkaSzebKpq3HRebCYe4akkMY6gi5KrNa6uyV4dXZNZkxYvGtT+RBo61lwoadZlug9pVu3UYVQDsLlszlLruyKLqtQ6rbhDrXF84w=,iv:TRxpwCHXeadlcmcQRCPRO9xPcq+Uw3PxSfOuSmyidyE=,tag:e3R1BN1/C+0grO3vYXCctQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
