base:
    userPassword: ENC[AES256_GCM,data:uzbuf4cWuYl3HLCRRqvlzButLtDEavlbfM9F899A3KaddV4a+JxoKKIt0D1DB5FKEDvRab5NwBsNC8ttopBDauMEK6cojHw6yQ==,iv:D8i66+rvjpULAEOQ93jtdHXP0xISyvGFKbkBCiLb9v8=,tag:qM/+0g+SvU+a3FB6yX9fJA==,type:str]
sops:
    age:
        - recipient: age1gvfnvnea09c8nqg7jf6m6e04e0kz0w4w4fvms00226cf7806sa2szcm46s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5UHVaUlZFOU9sYUVMR3k5
            SEltRGNrM0Mwb2swZy9Pb1V6cWdBREJVT1FNCjNLQm9qQ1lVOWNITnJPbkRQZGlw
            SkUyVFRrd2JQN0ladmlUOWgyUmN0VHcKLS0tIFhVN1Y1c0pLSjI4cm1nc2dydEU3
            Q1lack9MS0YxSXlVZ01iaGc2b1RySFUK4DrXGW3C0OIcLFEEDCR67apIq4vjc+1f
            JEuCk3epN2KP1RuXyHVLTFvUaLcP9hfWHtuOlcyvtnpFllOJHoIP6Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1l4sknz73q64rz2gy59d92twvs07p3tql4utx77fudxt0qsrl24nqqk4fqf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5VjJscjhxVFo4cGV0bzZl
            MFNMeHViKzFaUWt1RlJkc1VsQUs2RmN6b1hvCmVVZFVuOS9EM2cvdldxaUplbS9G
            T2RHQlA0S0M2QzNSb0xZYmNwcVJDODgKLS0tIEZLL3BLaTVpVnVWenA5MzFDUFNl
            eVFFS25meEt0dUJoMTAxR0pQMnNZRzgKxTasLL4qcOCo0TrQvoxpRZxR+B78bdj3
            o8X2YOOJUOkH74ghCy1b/SrL9xLYx1GhTEeT/EhDuQLjFigb1fDPBA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ma0e5ap4pdqmz4qj7rttlrk56mcvka0tuvltgp7dcv73fu6q3q5qj99gun
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNb1E3dW1KWTVlZXdHYldo
            Y1hOclBXYlhhdHR6Q21CWlhSd25ST0hrMHdNCmZrVXNieTk2cmsva2NkbTZWM08y
            dHRlNDh0Y0I1aG9JQ1JlU1R5RVVkd3cKLS0tIDRJbHdNemxhZ2pNZU9qalJTUDlI
            eExVWnBpcmJzdmxrZjM5aVNwQWlyK28KArwnM6yz2JReMa1GhL/lSDwvy9OZDooO
            J/oRu/AhJzEBGr9ODwGkDX1zxiYZSbA6CYPty0kuQXlx+Sw41zDbwg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1tl35pllv9mu4nzk8hpa2uuul96njqrcttg4hw20902saf3uynueshux230
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwL0dNL25pTDg0VG5naWQ2
            TjJ4S3AwOFpCZFRJZkZJL3M4Vm40cjV3RFFrCm1YeUVNQW5VSnJiN3NFUi9PWkhP
            U1h3QnpSeGxZNG9ZSnY3TmFrWEhvY3MKLS0tIFdITFZUYzYxMHJEVmE4UnBvaTJQ
            cmI0SGJsS3RKSWpxRi9BckpKVXdWdncKuYs4YpEVNUqoz5yNX9UlkKMcRQ2u3Cys
            +Hjz8g9tVtToYnp+4kbXxA/aDW8zgYa64jeYapTJEPqKOvEtkmyRuw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1525qyyhynpsqq9uee9yqhkt02kqnmpm8w4nyaw5wraewwrlycdjqg800wp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0bzB5Zit6cGJ4TVVCaDl4
            RXNrV2JtKzdSZmhIQUdOdWk1Um9hWjhKSmhnCmlPNzFpcjNXN2I3TjNKOWFTdkEx
            NzBzM0VzZHZsYkFXS0pOS0Z3OTdaS00KLS0tIGdWM1E2ZE8zNzBTczJDaithL1Mr
            OVhuWnFQd0ZRVjc0RGNWaUwrY0JoSkkK2JlS/mDOpWuLT9LRW+lXAgwoDXtteRuw
            FojyLDw9klVKOz8yp92NV+sFskpajKKuu3bUeOVKJ2ryCTyZh1UkAw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1f9y45fnympaytza0q59xzpqtqm6ac8uwxe55vc37xdllpwdacq6sy3wv3h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsVlNzR0FTVEloSmgzR3Qv
            K0plRkFxSWNvYmdyQUdnUnViMXo4MkRLcWd3ClF6NE9KQkx5WFMzZmkya091eWFY
            M2ZzRlp1WDg1T3I5bzdqZDh4ZG9qeEUKLS0tIGlPL295MFNMdXZWV3pnZ2g5UWht
            VkE0a09ua0Q5dlU1ckdyN1o5aHFzUFUKYKModcbi7ryIOIQUbhyjhH33M0yd3QyC
            UkfrlGDzCWLV9+KSNWdnApCGWXGYr9M8f3YhrDh+GHrdSGB4JVxl1A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-27T09:52:07Z"
    mac: ENC[AES256_GCM,data:eDniaSkuBMuU1Te39/guKH1anN6N7mmqIMwj7LckJkPvTaBASstaRuJzrQpHjWQv85pLbPLPkaSzebKpq3HRebCYe4akkMY6gi5KrNa6uyV4dXZNZkxYvGtT+RBo61lwoadZlug9pVu3UYVQDsLlszlLruyKLqtQ6rbhDrXF84w=,iv:TRxpwCHXeadlcmcQRCPRO9xPcq+Uw3PxSfOuSmyidyE=,tag:e3R1BN1/C+0grO3vYXCctQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
