base:
    userPassword: ENC[AES256_GCM,data:uzbuf4cWuYl3HLCRRqvlzButLtDEavlbfM9F899A3KaddV4a+JxoKKIt0D1DB5FKEDvRab5NwBsNC8ttopBDauMEK6cojHw6yQ==,iv:D8i66+rvjpULAEOQ93jtdHXP0xISyvGFKbkBCiLb9v8=,tag:qM/+0g+SvU+a3FB6yX9fJA==,type:str]
sops:
    age:
        - recipient: age1gvfnvnea09c8nqg7jf6m6e04e0kz0w4w4fvms00226cf7806sa2szcm46s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxaG4ySUhxbE1zUFd2di9L
            STNhc1VQcDVaaUdobmtBczhzMTlBSjlHaW04CksxcGd6MERVdjZGSm5hOEVtWVBo
            TkdXYytkOFZiZWRUeXNLeDEzc3QwQ28KLS0tIHhUd0VzcEt3NTFPQVdXWlR1S2Fl
            VG93RHd1M3hVQ3RObE9ScFlxVWl0YUEKmBR4NzHsuf8bC7aUSToLydDl1GCtBbQC
            y7THcQfRFocU5sHIV2BJqfQy1qro6/7AGWOwM1Se+t6KjU7+nDX0VA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1l4sknz73q64rz2gy59d92twvs07p3tql4utx77fudxt0qsrl24nqqk4fqf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHZjdzS1J2T3FOTWxvMVVT
            d0E1Q215OFVWQ3ZPTWNyclQweGpiOVNQcTBrCjFVZDFjZnhaQWg0NVdoK0M4WWFK
            ejRiZFZ6ZWhxaUJHb1lnNDFpaG1NV0EKLS0tIHV2NmM0SlphekczSEdMOWZVaHNi
            TEliNVNubDUxYlJ4MVhQWTJIenNkSGcKxsO6ZIu+Plqj0MmSG4l0aQrh9y3e3EOy
            5aW5gLhMvGXRJ/ZrcLfQbntYnPY4tBww5RU/UNj6LCEYlnhjC4FGIw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ma0e5ap4pdqmz4qj7rttlrk56mcvka0tuvltgp7dcv73fu6q3q5qj99gun
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKTmJrRFhxZUREV3hLVjFG
            eFYySVZWeWZaM1BENGtUUEpnbm9yKytyejAwClNQS2FtaEYvUEVDRk1OR3ltcDVp
            ZlZMd1dDcEt1WjB6WEIvOW1uVUlqRlEKLS0tIDh6SGd5TGxxRmwrMEFiZHQ4Zy9I
            U0o0NkFleUdDV2l3UmxvbWJ6UVliUU0KbapsevXtGA1ld4B1wF8q/GKGqHT/yZzR
            J6zenMNsv2PoqEYjJj2yQaO9qzK/p2FVhQ8nFlDJIYNRgEPq2hbESQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1tl35pllv9mu4nzk8hpa2uuul96njqrcttg4hw20902saf3uynueshux230
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxT00rS2VnUEpKQUhzMzk4
            TUxvdXdYWWwwZzRMUU9IY1BOak5mc0xCdEVFCkIxQUxjM2dNdkZDSjJvUFFRR3lo
            ZGxSaWN2NzlUK0RtK3FjZ3F1TkFIam8KLS0tIERLZ2VLQXA2dHFEVWVNN2pNRzdm
            TG1zZFE5VWwxMjI3VUxHRzZQMkw1WFEKzkx2Emosu0Ca0rcBEzkshZXpReDNwC+w
            p5zNjzqhsAxc/njXdE97jpTQsYlrKPE6zCqerxafiW0GJ8t+7t8jJw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1525qyyhynpsqq9uee9yqhkt02kqnmpm8w4nyaw5wraewwrlycdjqg800wp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHNGorNWZJSUZnazZvWHQ1
            dkdLMFFqSjI3amxHckNQbmpRU1dTSmJnb0NnCkRNZExNVktib3l1ZXBiRVVtQits
            SUdSc3g4MVQ5bWt1OTNKTThIamwyanMKLS0tIEh6d3JEOFNRYk04QzAyWWNvb2tx
            dlR1T2U0MHFyN0tJY1ZYeURUSzd0UXMKYciW3dbM/g56BX8gRbl5FOMMaC78k+c1
            ihV3OleUrAqjmSAnHV2j8MDlicMqHQg315D5+JsUhxuM02is/ZEThA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1f9y45fnympaytza0q59xzpqtqm6ac8uwxe55vc37xdllpwdacq6sy3wv3h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQSTAraHBLUW5pV1dwd1Bv
            cEZuU051T2pva1JDOTBwY1N0Znk4NUIrVEd3CkR3dkZxSkx5MmE0Y2ZTazFUaHFM
            dThSbFdTUzZDbGJSeS9mRHdobE0xelUKLS0tIDdWWWI0TGx6dGVzZkxFcXBSdHJZ
            dytubWtRcnc2ZVQxQlFNMExxUWRVdE0KlceQiQjaT8AK3Vg0Pofb/Tj8AOooiydO
            EyU/8DJoRgEu0CDhdnz+3IfaN1E9eps5J2Av+mecYxPUJSkx54LLFQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1v5smpsnjafylktdmxga6kmjtwawcd8veeq7my88ltdfss9x2nfaqq70ske
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvUC9nRi9OWjZyTDhpdVlK
            RG1CZUdTN2ZQYllJY2RtNWF5eXB3cHFQSnhJCjJocWxMMDA1cnQ1VCtHRHU1ZEZq
            cERVZUN1eE51TmtucWZSTHNPS1pYM1kKLS0tIHBjQ1JCejZuNXBpeXhmcXBzdGRO
            QVhIaHJpRnFkQXVtVU9wK2lWeDFuWncKa2PmVKKBb9NX89yZfGeCZYtlFopDT+TU
            Z0VxWWu9Vn/c2+oaAsyeupv2r8m6pF+p/X3M3o0bWohAGYOH8gaUAA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-27T09:52:07Z"
    mac: ENC[AES256_GCM,data:eDniaSkuBMuU1Te39/guKH1anN6N7mmqIMwj7LckJkPvTaBASstaRuJzrQpHjWQv85pLbPLPkaSzebKpq3HRebCYe4akkMY6gi5KrNa6uyV4dXZNZkxYvGtT+RBo61lwoadZlug9pVu3UYVQDsLlszlLruyKLqtQ6rbhDrXF84w=,iv:TRxpwCHXeadlcmcQRCPRO9xPcq+Uw3PxSfOuSmyidyE=,tag:e3R1BN1/C+0grO3vYXCctQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
