base:
    userPassword: ENC[AES256_GCM,data:uzbuf4cWuYl3HLCRRqvlzButLtDEavlbfM9F899A3KaddV4a+JxoKKIt0D1DB5FKEDvRab5NwBsNC8ttopBDauMEK6cojHw6yQ==,iv:D8i66+rvjpULAEOQ93jtdHXP0xISyvGFKbkBCiLb9v8=,tag:qM/+0g+SvU+a3FB6yX9fJA==,type:str]
sops:
    age:
        - recipient: age1gvfnvnea09c8nqg7jf6m6e04e0kz0w4w4fvms00226cf7806sa2szcm46s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjYUpCc2VqL29QY2tMRy9E
            RVFtVllHb3B0N3hwMndPZk5aNW14YUo2VEh3CmthaXhqS2VxUUdwOVpJcXdDR2Vx
            T1Z2T0N4SmhnTVo5OTIvSExHVW5rVU0KLS0tIFBuY0ltZFUrUXJuWHpHUlU1OUxN
            WVpTRjFWcmNDUTQ3Vnh3UldERFVPN3MKgnxQ4aE14Puwcjf/fUhAl56sue5i0jt1
            MOoWoYRbxiGwD7o7NkBEvuruIsdomSDsCsvvkhbLrYc7YS6AvAwR9g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1fjuvtyar38325jh7cxg88tgylkpxamm47vk32m33h454n03zzezqgs84e3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCYktrSkUvcE8yZDB3L09y
            UjJRcmRNTFZ5cGVmVWtPTVg4MUhwRFJJZVM0CkwxWnRXZkdJUm9zY2k0bUlYeVI1
            K1ExeWQxY3RjNTQ5VlRNWTVNRkFaQkkKLS0tIHl1bEpFdE11ZFVBSVQvY2lPbjBh
            MGJPc2F2ZTlURXJqekVkNDBuMFBlR1EKR7g6P+NFIE/chZ+Hj89D08l4iuGRTH74
            f++I9cX+OOQ62s1M81q1a/hjUlk+QGKcRfOrAdNZgpf1dywn/zD7ug==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1qdvcmhrn9w6lw92ta2vmh55t077m38gs4ksez489ztvnfqe03gxqzy57rz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2bUszTVllYVlPa0JuRTlI
            T2pPN3N1Vlk0VUs1WVN5MW5pMVYvK3Rzd0c0CnQ0Uk5UOVdHeE9UTGhwdGppR2R0
            MGh6SDlPZTluOEhlWmlWZ0FSK3lJUFkKLS0tIDRWUW03SGJGOUJyemtFNDZvWXJh
            bmkxQjJwN2lZbTFjWG1XNjhPRUs4QXcKBLP3IFYGZjotgHgfo2b6IMAILhpdoT3B
            ZuVguAarFu72H0JMQLbdoT4mk4smXo5UeQgdMRQCdo5Idv3sW3fwmw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age160pcykckysy5j9tksqpm3yr5l70xrj6c070ea3r39c6gza94hg7stnjkhq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3akpIMS8vKzZLcEEveDZm
            aDkrcVFWMUlQK09VazdOY2YrbkNncTEwb2lzCjNNS1Ywb0JkYTd2OTd0V3JjWmNW
            RDBjQW9DSnJiUHliR3RCeEpLSTduZlUKLS0tIDZ5ZVRvSnlzeG5mZVVVb3NZT3Zn
            WFJ4dkR6Z2s1ay9STVpaTkhRc0JNeEUKJW9T4Tdjla6puYerBTyM83YS0tzdPpMq
            QSpE7sGGWdvY3l8tYcnBC3gSZT7peCuRAl2MbBB0c2Nq04GvSMCOwQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age19th9vdcnftl5y2dwt8sl89xy7w5trvemxd7hm55glvqcmhh0348qef7pz3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWVjF1V2taUnNFWmpKOC9X
            ZEFsTVRaTXRPaW1RamxEMGFCN0pWWkdFd1hjCjliQ3k2YklqNEpKVkFnNUxjcXc4
            NXEydEVENWx6SFRpSDhRdUowbjdPeVEKLS0tIHc1SWFuUHRPd0JJYXNGSGlEVnZM
            cWZOREJvYWlmQTlqRjkrWWN4SmJTN00KimLlahcsLRskZcIuO+41uHy5evDnxpZA
            gQ3DsGiyQ7oyawbEDChxisAwgGeWWg08YN41gvyHEg6/CjC6WVyzlQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1j0e4y7cy9rutuvr6spkell45s79m0gwm27q93m6hymhmshkf65wsm4pfnm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLN0h6bGFsNjhpNlFiS3FW
            RW1JemZ3NnlsRG9rUElzUVRnRnFHbEM3TVdzCm0yeEw4VEhvZzVTYUxXNWs3UHlo
            NHVhL3pjZ2ZDbDFoMFM5TDFSaENrNGcKLS0tIFE4aWFFM1hNdjBLNmgzNWxYM0Z4
            dmVPdTJZd0pMNVpIWmFvMUY1c1N0aVUKM03HGx4JgAAdLJPZPcxl6zDlytCBdnyS
            xQD1DJOA0ud1D61M5m5pK7JHoIEs6NLMLevF6II7GFoLFN9+EaNMwA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1den7w9ceeyprqug0zmefjfmspaxjee6j0rmpg9r0e66d2rfu73uqk4p0nh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpKy84ajJVS1RaMHlpQTJQ
            MmxpY2N2MkJhbXllcWR6TlpzTDJFVU1vMjJjCmxucVV4S2g5WDg5SllpVkhac2Nn
            bnlJK3hKK3ZkT1hxcXZqRjJubTFHOGsKLS0tIDRBVXpmcDMyVEVKbm1iT09zbnBU
            RWZlbDNnb3E2aTJWdzBNYmhTbUNuYmMKoDmx+sYmIqrjHteVJotNIyScetiBZ+bn
            nq2qjzRet21f+Dr17IZ7L04eV2rhl5g3SVF5kbCTiaOm1LQGEBBEmA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1v5smpsnjafylktdmxga6kmjtwawcd8veeq7my88ltdfss9x2nfaqq70ske
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLZTVmQnJKckRFMzl6MWVE
            NWo3NlpoTDZMRnBDRUpnbkM5T3Vhc1lVb3pvCjNyZmMzdXM3ZEpscW5SYkZmT0Y5
            QXg4KytsMjdvUzhHQXBsMDF1aGJTeTgKLS0tIDZJelhGakR3aGI2T0YwVndmdXUv
            R0VVUWR5SDNMTE0xUmxKTW4ya3pZN1kKa4/lyQ+AOaM4qHtZJfhHjHhKWWELGoR0
            94cBOcgyk1Iz1L+Sko4cdPSr//A82IdeFbKWn3tSzyh6/LM+mk27tA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-27T09:52:07Z"
    mac: ENC[AES256_GCM,data:eDniaSkuBMuU1Te39/guKH1anN6N7mmqIMwj7LckJkPvTaBASstaRuJzrQpHjWQv85pLbPLPkaSzebKpq3HRebCYe4akkMY6gi5KrNa6uyV4dXZNZkxYvGtT+RBo61lwoadZlug9pVu3UYVQDsLlszlLruyKLqtQ6rbhDrXF84w=,iv:TRxpwCHXeadlcmcQRCPRO9xPcq+Uw3PxSfOuSmyidyE=,tag:e3R1BN1/C+0grO3vYXCctQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
