base:
    userPassword: ENC[AES256_GCM,data:uzbuf4cWuYl3HLCRRqvlzButLtDEavlbfM9F899A3KaddV4a+JxoKKIt0D1DB5FKEDvRab5NwBsNC8ttopBDauMEK6cojHw6yQ==,iv:D8i66+rvjpULAEOQ93jtdHXP0xISyvGFKbkBCiLb9v8=,tag:qM/+0g+SvU+a3FB6yX9fJA==,type:str]
sops:
    age:
        - recipient: age1gvfnvnea09c8nqg7jf6m6e04e0kz0w4w4fvms00226cf7806sa2szcm46s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWNm01VUpobVhyclo3ZWJR
            cEpLeTd1ZDVwM0JyYU91S29iVDdBWWRIenpRCmF2TVFCWHFYVkMwUDNtS2kxRlRI
            QUhYNGJsYjdUVWY0U3VTRER0Rjk3Z00KLS0tIGE2ZXpKSUJ2VGZkRUxzSXZFSzFX
            K2wzNzFoclltdXl5eUdsdEV3OTNBdVEKiPE01aiQmaih+FZTd9xZw6RQDMKM7MkO
            fDrCmutk8j7VZ3+zkKuxXQi5r6KvrKnefple6hvk5zhvsJmzEb/iPg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1l4sknz73q64rz2gy59d92twvs07p3tql4utx77fudxt0qsrl24nqqk4fqf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMRjd0c0hWVUVwUHo0aWph
            SHA4aVZSWkRJQ0xKaHo3NDVrK1Z6K1ZtWERNCmdIN1JubnZWenhmVStXRE96NHg0
            ZzZwM2hDS09iSGpOTlh4VWpMZHlLdU0KLS0tICtYbEEwQU40RnZySi9YbzU4dVhh
            VHpXOExvOVlFRmYvQzZ5bmhaM0ROemcKxbBesiTZZD9mEwJX0K8PYq0DaoonzZut
            VIiIryrL2jxfls624sMov5qzrQgRaDxWAvBbu/tlXyAzflK/YHj2MA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ma0e5ap4pdqmz4qj7rttlrk56mcvka0tuvltgp7dcv73fu6q3q5qj99gun
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDTDJtVE1EdURhdmh0R1Js
            YlhFSWZKeVUraDgwcHRQN09zN2hFV2FUa0dvCmxrM0lnenJSczlTWnFWQ25YU1NT
            eVV3VjhLT2xmTFkzbUxtRktBOHkySkUKLS0tIGlFU2RRK3RCRjR6cHFXdzJLR1ZO
            TWlLRFpLV3N3T3JlN3JFMjZEV3hLc3cKkqSyk1b4BMrppTqRMVLSXYt/iwfYZEnj
            GBpnyTTAiTtrN8KoKppK0xLy6emiEjxHA8Uk1qT3nXMu+tEDrOx/iA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1tl35pllv9mu4nzk8hpa2uuul96njqrcttg4hw20902saf3uynueshux230
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJVFZPby9uczRlSkZVak5H
            azFxY3NpaG5RT2FydngwcHEyOUZtVlc2RzM0CkZ5YVZialBIOTEwZCtVYldjY0tp
            a2E2ajBteTVldlhReHlGTUZsRXhOVkkKLS0tIC84andaTzNBZFZSTERjbUNMVWsy
            RUxrNGx6Q01QbG8vV251V2lYc1Q0VFEKvQHJSoK7DilKo6/xkRo0Z6lSh6wddHH/
            undl80+G0ipHwa77hFkxYD5MeNXpnHwavqmZURt+Jme81IF4nNpPoA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-27T09:52:07Z"
    mac: ENC[AES256_GCM,data:eDniaSkuBMuU1Te39/guKH1anN6N7mmqIMwj7LckJkPvTaBASstaRuJzrQpHjWQv85pLbPLPkaSzebKpq3HRebCYe4akkMY6gi5KrNa6uyV4dXZNZkxYvGtT+RBo61lwoadZlug9pVu3UYVQDsLlszlLruyKLqtQ6rbhDrXF84w=,iv:TRxpwCHXeadlcmcQRCPRO9xPcq+Uw3PxSfOuSmyidyE=,tag:e3R1BN1/C+0grO3vYXCctQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
