base:
    userPassword: ENC[AES256_GCM,data:uzbuf4cWuYl3HLCRRqvlzButLtDEavlbfM9F899A3KaddV4a+JxoKKIt0D1DB5FKEDvRab5NwBsNC8ttopBDauMEK6cojHw6yQ==,iv:D8i66+rvjpULAEOQ93jtdHXP0xISyvGFKbkBCiLb9v8=,tag:qM/+0g+SvU+a3FB6yX9fJA==,type:str]
sops:
    age:
        - recipient: age1gvfnvnea09c8nqg7jf6m6e04e0kz0w4w4fvms00226cf7806sa2szcm46s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3c3g4WkhWVzZBUTlVWEVv
            L2VLQncxUlZCayswSmI1bnMweFVHYUJaNWowCjdsK21KbnRKMDVQVnl6UDhHY2tF
            N1NwY2hMNE56VDRiQnlYSTFNVkxFVFEKLS0tIGJQL1ZBYWMwNmU2QS9kc1FGYncw
            Y3Q5aXc1MjRMdHdtZ3J4cmlialQ1Sm8KHCjgRUmE2p8uAenlncAg3MRkhKLDDMj4
            Pk8x17crDfOpnqF8gPBII3+VYu9wKnU0gvpY+41baXXN32zgHUSrPw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1l4sknz73q64rz2gy59d92twvs07p3tql4utx77fudxt0qsrl24nqqk4fqf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNcXlZK2hYRlNzLzlHUG1K
            bmZBS1NzaUlyNUJmQlo2dkdBWXRhbXNvVlEwCjdnL3c4a0svZTlvOG9hcUdQWmV2
            Vk9yQzZjelhBTTlUTjlQTVY2Yzd1WU0KLS0tIEtrL3Bhcy9nMytPa2Y1ckFCdlVw
            V0dCdC9wa05Id1NlOFFMY1U3clkyZ1EKSHVouFqFIobOkkLA0kgHBpVlzmAOaWnZ
            BHdClEhOU/ecIvG+qofNlzXaqM3Q8bbeXHB6zrjPyAzI61NzJCgNdQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ma0e5ap4pdqmz4qj7rttlrk56mcvka0tuvltgp7dcv73fu6q3q5qj99gun
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6SUxwUm05bXlmK1dneHJu
            a3BYdEFObXZ5UmJFckEvcGEwOGMrNi9id2pjCitJME1jNTJyUElFdkw0SmdsOUwx
            ZlBsNXFqbVRMeHYwUkZWM1UvSVEyMFkKLS0tIHpYQzM3WEJqYlQrVmlUOG9oL0Ft
            ZWhBZEovaEFrZTdyV2ZPeXZsZklmYmsK29CzQob3NTzjFfFtKko5EcyxisbJCiPf
            uBiHHzScGiEc9bq2VkP6oL8xsyTluV42Y61zPeuURmQ5l3xF2rpfpw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1tl35pllv9mu4nzk8hpa2uuul96njqrcttg4hw20902saf3uynueshux230
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3V0I1Zk5zeWcySUZ1K2gv
            Yy9rUFZhQjltV1Z6MC9xY0RHcjl4aGhoemgwCkppQVM3dzBsOFMwYkdKWHcrLzFS
            b3Y3Kzh6ZWVldG1XblhaUEdqNVJTTmMKLS0tIG54V0c4OFk0cHJWbGZycXlaLy9J
            TTluMGZBRnRxYVZsSnBaOHdZRjVjTWcK1M6d175CIhWP41Pbv4ZIrHYIe8id51L6
            EudRlMZgGQz++BZ3vnZhPu9rojammPio7k7aDreKnGZ7j4LlAbsRsg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1525qyyhynpsqq9uee9yqhkt02kqnmpm8w4nyaw5wraewwrlycdjqg800wp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArYm9NdzZmb3dYb0ZXTW1Y
            VG5nTThFYUJZdnJyYmhZZ1FEMVFlajlCL1IwCi9YZnpybXlGRzBiZElHNGx1OXgx
            dkxhbkYwSlBEODhlc1ZZY2VMOG8xWVEKLS0tIEljQjFjT04zQjRPYzhBUndwcUg1
            Sm1rVEtwaVk1QmY0YzR3ZkR6a041YUkKONN7gBgOPpRGTKqIUy3vhTB0RXUPL/OG
            MPYfw9Mfasl/KzaktC3BtFA+IEBw7ehwuWRPv0FAFBHeiR3Htt3hww==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-27T09:52:07Z"
    mac: ENC[AES256_GCM,data:eDniaSkuBMuU1Te39/guKH1anN6N7mmqIMwj7LckJkPvTaBASstaRuJzrQpHjWQv85pLbPLPkaSzebKpq3HRebCYe4akkMY6gi5KrNa6uyV4dXZNZkxYvGtT+RBo61lwoadZlug9pVu3UYVQDsLlszlLruyKLqtQ6rbhDrXF84w=,iv:TRxpwCHXeadlcmcQRCPRO9xPcq+Uw3PxSfOuSmyidyE=,tag:e3R1BN1/C+0grO3vYXCctQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
