base:
    userPassword: ENC[AES256_GCM,data:uzbuf4cWuYl3HLCRRqvlzButLtDEavlbfM9F899A3KaddV4a+JxoKKIt0D1DB5FKEDvRab5NwBsNC8ttopBDauMEK6cojHw6yQ==,iv:D8i66+rvjpULAEOQ93jtdHXP0xISyvGFKbkBCiLb9v8=,tag:qM/+0g+SvU+a3FB6yX9fJA==,type:str]
sops:
    age:
        - recipient: age1gvfnvnea09c8nqg7jf6m6e04e0kz0w4w4fvms00226cf7806sa2szcm46s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUUTZhR1ZUM0xUWWFUQnNj
            MUdjM1BOakZTR3d0Y043dzF6SlBCa1Y3UjJnCkwrQk0yRC9ycjQ4S3JCZlludmRP
            ZEszTGJUNEV3TkVkdU9hMG9IRllkbXcKLS0tIERScWNnODVncUErOE9PdEhYaHVx
            a1lNbVdrWjNXYXVnT2Z1bWVsQnM2K2MKau2/pf6PIqklKaUcXQRxKVgNhh/jf4Z+
            ZVUGFnUoPAF8YzBBekNlaU5UdETBrcylL87+hFoMwWhRjiwM6vjxIQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1fjuvtyar38325jh7cxg88tgylkpxamm47vk32m33h454n03zzezqgs84e3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTSmVDKyt1QTBGWWtsYUEr
            bFNOdmx3eU16U1MrTUtLQ1AvQ3Z2cmoxdzFNCm1WNVdweGcvK2hYMGZnd004YW9U
            aHVGYXBCdjlqUXNHdkVKUmNLMnlIMkEKLS0tIFlITEFZamZJUENZTE4wNmlUR3A1
            WDViSUI3WTVEZ3ZuaGEvSGNjUWpBa2sKbB+wJRb+IMdljM4s/HKc4AEXbzQNiEGb
            l0n5kJ/YwpiYx0QwPn2RlYjtAYFs+j2DAeO0JJRgZpO35Qy4vlFcRA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1qdvcmhrn9w6lw92ta2vmh55t077m38gs4ksez489ztvnfqe03gxqzy57rz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnNnZmWEMwcjRqZDd0WnRX
            Q3R6ckdkUXhnZEVLYlorazJYZVlwN29GN1hRCmJ6RGhpSkI2K2JOQVFxbi9HdzVN
            RCsxc0k1cjdoN2dtNVF2UXRFY2pOclkKLS0tIFc0QUNxTUdmMVhCYWhwelhYYmsx
            TERHV2huVkdtbW5NNWNTaWpFQ2RpOE0KpSGG4r0kGodcpDPHvbCdPoHJ9/IAMlQf
            GzRc+rS1AF04he1g0ZXvfpKheYnG8Iwj1qo9LedgBsUHCmsWYhUi5A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age160pcykckysy5j9tksqpm3yr5l70xrj6c070ea3r39c6gza94hg7stnjkhq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJZlVza0s2ZHVEUERMRVZX
            NnRRQWZCL0VpOXRiMWhyZDYzblhQbG9ZVnpZCkNkSG12SlYvSW9makErMVFvbldp
            eXB3OEhVOHlNNlNURkg5ZEFWcEVNWmMKLS0tIGhXWDh2Ym1uWWhlYjJqTVdXQUN2
            ME9iSFJjbVZJSTZOa3FpVUFZZjkzeTQKgjD8xFWMdaKU43AOe5FoCcqatx+6eUQS
            RUAck4CGT8DFlP9jj7iv2syyXb9R8dIjfZQJ2UfIXeAzYglnJhGTkw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1tl35pllv9mu4nzk8hpa2uuul96njqrcttg4hw20902saf3uynueshux230
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5aldzOGNPa2ZNMnZES3lj
            Q1dHK3Z4ak5XR2ZXOUI1cGxIbVBPZVRWZHg0CjFMNTNLUnp0T1RjM3F0OGprQms4
            ZGlNWFZOTWYzWlF2eXVQU3crL296em8KLS0tIG1qUWdoazRUSnpKbTZqUUFDbkgr
            R3lGZWovUWJZUnQvbWdHeEN0aE5mbUUKGL3QoCJoAKOgWu7GrT81Xqi1fOb4bp/a
            egw+XW7lScfyZawkE63WlPOTPd9jHXGMfKBqKS+wgMSIE+gH93q5Og==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1j0e4y7cy9rutuvr6spkell45s79m0gwm27q93m6hymhmshkf65wsm4pfnm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqOU5MY09Xdk5kbUg5UUNB
            M0R0N1J5K3Z3Y1VEZDR3QWp1RW9BZzEvYmdFCkt2bVVUb0FnQ3dibXd1dmNScUJX
            T0JSbEhpR2VmZkFLdlQ5MFdYaHgvUzAKLS0tIG5MMlljNDAzVUJRMnFIY2Z6SnhW
            cHJMSVJMUDdPRE5ER094VFpZenR5eW8KkKw0HSNv+DWbevQw8xAmxXrUM7Jnkg72
            QM0DcpoZXP3kUmBhpabKp8R5vCsW2PsiIEmBO6Z7wGr8j+JvN6Sixg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1den7w9ceeyprqug0zmefjfmspaxjee6j0rmpg9r0e66d2rfu73uqk4p0nh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtQW1nSGtaVGJJSFNBb1pK
            L2RKUlUrRGtTUDdSWVcvd2xLNXZOdHhUK1YwCjZsUzRYR3lBd1Z0cmpNcHFWY2Iy
            UHpVRGJxNWdlT0dEQ1d6andFYUFJUk0KLS0tIGhCcE1kc2FFQlpEWHdCQXpoSElG
            T05aNHhSNUtzWU1BSk9FanJwQnZNU1kKp8Cb8fFCs8ejhVbJLhNkFuNP7f+L6Jkr
            69rLnZ/9GlSOE+/WDrPu9NtNgnoUhnkIVPIYuGYzWDtZLIvnRkfq3Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1v5smpsnjafylktdmxga6kmjtwawcd8veeq7my88ltdfss9x2nfaqq70ske
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFYkNlMEVVTjZuakZzR3B1
            WFA3R2ZVbE1tdGxPM0thNU41anBvZGxzR0cwCi9BNXF0U213ZzNNMllBaHJCZTZK
            STBGYTNnZFZnWlpnWURUdUVRd3ZDb28KLS0tIGxBZmNhWnRjS2tMNFBwZTlEWlM1
            QlFKZmwxUUNjSkFRbUhTdnhjTG5QQ1UKCnudQTnP24yQJImsDdOe2wcwEu4bQoR2
            ixcUsQQa0ZKCJztnYE/p+ejXFqyAOs9I7fMDhMNOqHIeV27IjRtkFw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-27T09:52:07Z"
    mac: ENC[AES256_GCM,data:eDniaSkuBMuU1Te39/guKH1anN6N7mmqIMwj7LckJkPvTaBASstaRuJzrQpHjWQv85pLbPLPkaSzebKpq3HRebCYe4akkMY6gi5KrNa6uyV4dXZNZkxYvGtT+RBo61lwoadZlug9pVu3UYVQDsLlszlLruyKLqtQ6rbhDrXF84w=,iv:TRxpwCHXeadlcmcQRCPRO9xPcq+Uw3PxSfOuSmyidyE=,tag:e3R1BN1/C+0grO3vYXCctQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
