{
  patch,
  pkgs,
  lib,
  ...
}:
{
  hardware.graphics.package =
    (pkgs.mesa.override {
      galliumDrivers = [
        "d3d12"
        "iris"
        "llvmpipe"
        "radeonsi"
        "virgl"
        "zink"
        "nouveau"
      ];

      vulkanDrivers = [
        "amd"
        "gfxstream"
        "intel"
        "microsoft-experimental"
        "swrast"
        "virtio"
        "nouveau"
      ];
    }).overrideAttrs
      (prev: {
        version = "26.2-git";

        src = pkgs.fetchFromGitLab {
          domain = "gitlab.freedesktop.org";
          owner = "mesa";
          repo = "mesa";
          rev = "7f760b878f2686de303b5d07512ad3a2ca1ab441";
          hash = "sha256-JbaSZtxKJuo+Xtp783kU2m3dKGPczpTs3R0M/YqS7gc=";
        };

        venusProtocolSrc = pkgs.fetchFromGitLab {
          domain = "gitlab.freedesktop.org";
          owner = "virgl";
          repo = "venus-protocol";
          rev = "e94b12f301b9eb27ebead757128a18420b4f7994";
          hash = "sha256-bRpb8eSgfbOdfKOlxA4P23yEAr0Q7Iq3fh34gZnwKjQ=";
        };

        patches = prev.patches ++ [
          (pkgs.fetchpatch {
            url = "https://gitlab.com/evlaV/mesa/-/commit/e682bb001fc4e85ab191c1557692ebad5a4ee8af.patch";
            hash = "sha256-E5GItsdehLHxkgSUPQgfZxv67/+YVoTyMDr1738hq9Y=";
          })
          (patch /mesa/26/vendor-venus-protocol.patch)
        ];

        postPatch = (prev.postPatch or "") + ''
          # venus-protocol is a meson subproject (wrap-git) in newer mesa,
          # but nixpkgs meson uses --wrap-mode=nodownload. Vendor the
          # generated protocol headers like older mesa did instead.
          cp -r $venusProtocolSrc/templates $venusProtocolSrc/xmls $venusProtocolSrc/vkxml.py $venusProtocolSrc/vn_protocol.py .
          mkdir -p src/virtio/venus-protocol
          echo '/* This file is generated by venus-protocol. */' > banner
          python3 vn_protocol.py \
            --outdir src/virtio/venus-protocol \
            --banner banner
        '';
      });
}
