{
  patch,
  pkgs,
  lib,
  ...
}:
{
  hardware.graphics = {
    enable = true;
    package =
      (pkgs.mesa.override {
        galliumDrivers = [
          "d3d12"
          "iris"
          "llvmpipe"
          "radeonsi"
          "virgl"
          "zink"
          "nouveau"
        ];

        vulkanDrivers = [
          "amd"
          "gfxstream"
          "intel"
          "microsoft-experimental"
          "swrast"
          "virtio"
          "nouveau"
        ];

        libdrm = pkgs.libdrm.overrideAttrs {
          version = "2.4.133";
          src = pkgs.fetchurl {
            url = "https://dri.freedesktop.org/libdrm/libdrm-2.4.133.tar.xz";
            hash = "sha256-/Gj50LoupjyUMqKZ4U/qCfrXqKZugDn814AspZ93tPU=";
          };
        };
      }).overrideAttrs
        (prev: {
          version = "26.2-git";

          src = pkgs.fetchFromGitLab {
            domain = "gitlab.freedesktop.org";
            owner = "mesa";
            repo = "mesa";
            rev = "fdaeb5a757599841ec9c95a548f8849066bd2fc3";
            hash = "sha256-i5RDzDbR4lgwwaQ3DaSppdodKxZwBHjfZjcvRops5ls=";
          };

          venusProtocolSrc = pkgs.fetchFromGitLab {
            domain = "gitlab.freedesktop.org";
            owner = "virgl";
            repo = "venus-protocol";
            rev = "e94b12f301b9eb27ebead757128a18420b4f7994";
            hash = "sha256-bRpb8eSgfbOdfKOlxA4P23yEAr0Q7Iq3fh34gZnwKjQ=";
          };

          patches = prev.patches ++ [
            (pkgs.fetchpatch {
              url = "https://gitlab.com/evlaV/mesa/-/commit/e682bb001fc4e85ab191c1557692ebad5a4ee8af.patch";
              hash = "sha256-E5GItsdehLHxkgSUPQgfZxv67/+YVoTyMDr1738hq9Y=";
            })
            (patch /mesa/26/vendor-venus-protocol.patch)
          ];

          postPatch = (prev.postPatch or "") + ''
            # venus-protocol is a meson subproject (wrap-git) in newer mesa,
            # but nixpkgs meson uses --wrap-mode=nodownload. Vendor the
            # generated protocol headers like older mesa did instead.
            cp -r $venusProtocolSrc/templates $venusProtocolSrc/xmls $venusProtocolSrc/vkxml.py $venusProtocolSrc/vn_protocol.py .
            mkdir -p src/virtio/venus-protocol
            echo '/* This file is generated by venus-protocol. */' > banner
            python3 vn_protocol.py \
              --outdir src/virtio/venus-protocol \
              --banner banner
          '';
        });
  };
}
