name: "Cachix"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v25
    - uses: cachix/cachix-action@v14
      with:
        name: pongo1231
        authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
    - run: nix build .#nixosConfigurations.victus.pkgs.lix .#nixosConfigurations.victus.pkgs.kdePackages.kwin .#nixosConfigurations.victus.pkgs.mesa .#nixosConfigurations.jupiter.pkgs.mesa
